title: Pepe Sepúlveda
email: me@pepesepulveda.com
description: >- # this means to ignore newlines until "baseurl:"
  Arquitecto de transformaciones digitales.
  Enfocado en el equilibrio entre visión y ejecución.
url: "https://pepesepulveda.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pepe_sepulveda
github_username: pepesepulvedasanchis
permalink: pretty
image_path: /assets/articles/
repository: connellmccarthy/connellmccarthy.github.io

# Feature flag: set to true later to wake the shop back up
shop_enabled: false

sass:
  sass_dir: _sass
  style: compressed

collections:
  article:
    output: true
    sort_by: date
    permalink: "/:collection/:path/"
    future: true

  # Shop-related collections (kept in the repo, but not generated as pages)
  collections:
    output: false
    sort_by: title
    permalink: "/prints/:collection/:path/"

  products:
    output: false
    sort_by: title
    permalink: "/prints/:collection/:path/"
